---
title: Stackbit Exto Theme
baseURL: "/"
params:
  color_scheme: dark
  accent_color: green
  header:
    title: LUCA
    has_nav: true
    logo_img: ''
  footer:
    content: "&copy; Stackbit-Exto. All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
